"object"!==typeof JSON&&(JSON={});
(function(){function c(a){return 10>a?"0"+a:a}function d(){return this.valueOf()}function f(a){m.lastIndex=0;return m.test(a)?'"'+a.replace(m,function(a){var b=t[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function a(b,c){var e,d,g,q,v=k,l,h=c[b];h&&("object"===typeof h&&"function"===typeof h.toJSON)&&(h=h.toJSON(b));"function"===typeof n&&(h=n.call(c,b,h));switch(typeof h){case "string":return f(h);case "number":return isFinite(h)?String(h):
"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";k+=p;l=[];if("[object Array]"===Object.prototype.toString.apply(h)){q=h.length;for(e=0;e<q;e+=1)l[e]=a(e,h)||"null";g=0===l.length?"[]":k?"[\n"+k+l.join(",\n"+k)+"\n"+v+"]":"["+l.join(",")+"]";k=v;return g}if(n&&"object"===typeof n){q=n.length;for(e=0;e<q;e+=1)"string"===typeof n[e]&&(d=n[e],(g=a(d,h))&&l.push(f(d)+(k?": ":":")+g))}else for(d in h)Object.prototype.hasOwnProperty.call(h,d)&&(g=a(d,h))&&l.push(f(d)+
(k?": ":":")+g);g=0===l.length?"{}":k?"{\n"+k+l.join(",\n"+k)+"\n"+v+"}":"{"+l.join(",")+"}";k=v;return g}}var b=/^[\],:{}\s]*$/,e=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,g=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,r=/(?:^|:|,)(?:\s*\[)+/g,m=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,s=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;
"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},Boolean.prototype.toJSON=d,Number.prototype.toJSON=d,String.prototype.toJSON=d);var k,p,t,n;"function"!==typeof JSON.stringify&&(t={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=
function(b,c,e){var d;p=k="";if("number"===typeof e)for(d=0;d<e;d+=1)p+=" ";else"string"===typeof e&&(p=e);if((n=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return a("",{"":b})});"function"!==typeof JSON.parse&&(JSON.parse=function(a,c){function d(a,b){var e,f,g=a[b];if(g&&"object"===typeof g)for(e in g)Object.prototype.hasOwnProperty.call(g,e)&&(f=d(g,e),void 0!==f?g[e]=f:delete g[e]);return c.call(a,b,g)}var f;a=String(a);s.lastIndex=
0;s.test(a)&&(a=a.replace(s,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(b.test(a.replace(e,"@").replace(g,"]").replace(r,"")))return f=eval("("+a+")"),"function"===typeof c?d({"":f},""):f;throw new SyntaxError("JSON.parse");})})();
(function(c,d){"undefined"!=typeof module&&module.exports?module.exports=d():"function"==typeof define&&define.amd?define(d):this[c]=d()})("$script",function(){function c(a,b){for(var c=0,e=a.length;c<e;++c)if(!b(a[c]))return g;return 1}function d(a,b){c(a,function(a){return!b(a)})}function f(b,e,g){function m(a){return a.call?a():k[a]}function q(){if(!--u){k[h]=1;l&&l();for(var a in p)c(a.split("|"),m)&&!d(p[a],m)&&(p[a]=[])}}b=b[r]?b:[b];var s=e&&e.call,l=s?e:g,h=s?b.join(""):e,u=b.length;setTimeout(function(){d(b,
function w(b,c){if(null===b)return q();b=!c&&-1===b.indexOf(".js")&&!/^https?:\/\//.test(b)&&n?n+b+".js":b;if(t[b])return 2==t[b]?q():setTimeout(function(){w(b,!0)},0);t[b]=1;a(b,q)})},0);return f}function a(a,c){var d=b.createElement("script"),f;d.onload=d.onerror=d[s]=function(){d[m]&&!/^c|loade/.test(d[m])||f||(d.onload=d[s]=null,f=1,t[a]=2,c())};d.async=1;d.src=u?a+(-1===a.indexOf("?")?"?":"&")+u:a;e.insertBefore(d,e.lastChild)}var b=document,e=b.getElementsByTagName("head")[0],g=!1,r="push",
m="readyState",s="onreadystatechange",k={},p={},t={},n,u;f.get=a;f.order=function(a,b,c){(function q(e){e=a.shift();!a.length?f(e,b,c):f(e,q)})()};f.path=function(a){n=a};f.urlArgs=function(a){u=a};f.ready=function(a,b,e){a=a[r]?a:[a];var g=[];!d(a,function(a){k[a]||g[r](a)})&&c(a,function(a){return k[a]})?b():!function(a){p[a]=p[a]||[];p[a][r](b);e&&e(g)}(a.join("|"));return f};f.done=function(a){f([null],a)};return f});var atinge=window.atinge;atinge||(atinge=window.atinge={});atinge.window=window;
atinge.navigatorplugins=navigator.plugins;atinge.browserId=Math.floor(4294967295*Math.random());atinge.dataPrefix="atinge_";atinge.isArray=function(c){var d=typeof c;return"array"==d||"object"===d&&"[object Array]"==Object.prototype.toString.call(c)};
atinge.murmurhash3_32_gc=function(c,d){var f,a,b,e,g;f=c.length&3;a=c.length-f;b=d;for(g=0;g<a;)e=c.charCodeAt(g)&255|(c.charCodeAt(++g)&255)<<8|(c.charCodeAt(++g)&255)<<16|(c.charCodeAt(++g)&255)<<24,++g,e=3432918353*(e&65535)+((3432918353*(e>>>16)&65535)<<16)&4294967295,e=e<<15|e>>>17,e=461845907*(e&65535)+((461845907*(e>>>16)&65535)<<16)&4294967295,b^=e,b=b<<13|b>>>19,b=5*(b&65535)+((5*(b>>>16)&65535)<<16)&4294967295,b=(b&65535)+27492+(((b>>>16)+58964&65535)<<16);e=0;switch(f){case 3:e^=(c.charCodeAt(g+
2)&255)<<16;case 2:e^=(c.charCodeAt(g+1)&255)<<8;case 1:e^=c.charCodeAt(g)&255,e=3432918353*(e&65535)+((3432918353*(e>>>16)&65535)<<16)&4294967295,e=e<<15|e>>>17,b^=461845907*(e&65535)+((461845907*(e>>>16)&65535)<<16)&4294967295}b^=c.length;b^=b>>>16;b=2246822507*(b&65535)+((2246822507*(b>>>16)&65535)<<16)&4294967295;b^=b>>>13;b=3266489909*(b&65535)+((3266489909*(b>>>16)&65535)<<16)&4294967295;return(b^b>>>16)>>>0};
atinge.pluginHash=function(){for(var c=atinge.navigatorplugins,d="",f=0;f<c.length;++f){var a=c[f];"string"==typeof a.name&&(d+=a.name);"string"==typeof a.description&&(d=d+"/"+a.description);"string"==typeof a.filename&&(d=d+"/"+a.filename);d+="\n"}return atinge.murmurhash3_32_gc(d,0).toString(16)+atinge.murmurhash3_32_gc(d,2588935699).toString(16)+atinge.murmurhash3_32_gc(d,3237188224).toString(16)};atinge.url=function(c){return atinge.local?c:window.location.protocol+"//api.atinge.com"+c};
atinge.nullEmptyString=function(c){if(null==c)return c;c=c.trim();return""==c?null:c};atinge.setData=function(c,d,f){f=f?"sessionStorage":"localStorage";c=atinge.dataPrefix+c;window[f]?window[f].setItem(c,d):document.cookie=c+"="+encodeURIComponent(d)};
atinge.getData=function(c){var d;c=atinge.dataPrefix+c;if(window.localStorage&&(d=window.localStorage.getItem(c))||window.sessionStorage&&(d=window.sessionStorage.getItem(c)))return d;c+="=";d=document.cookie.split(";");for(var f=0;f<d.length;f++){for(var a=d[f];" "==a.charAt(0);)a=a.substring(1,a.length);if(0==a.indexOf(c))return a.substring(c.length,a.length)}return null};atinge.log="undefined"!=typeof console&&console.log?console.log.bind(console,"ATINGE:"):function(){};
(function(){function c(a){this.script=a;this.global=[];this.request=[];this.finishCallback=[];this.targeting=null}function d(){this.array=[]}var f=window.atinge;d.prototype.addSize=function(a,b){2==a.length&&this.array.push([a,b]);return this};d.prototype.build=function(){return this.array.slice(0)};c.prototype.push=function(){for(var a=!1,b=0;b<arguments.length;b++){var c=[].concat(arguments[b]),d=c[0];"string"!=typeof d?"function"==typeof d&&d(this):(d.indexOf("@")?this.global.push(c):this.request.push(c),
"request"==d&&(this.targeting&&(this.request.push(["tg",this.targeting]),this.targeting=null),this.slotEvents&&(this.request.push(["slt"].concat(this.slotEvents)),this.slotEvents=null),a=!0))}a&&(this.execute(this.request),this.request=[])};c.prototype.execute=function(a){a=this.global.concat(a);a=encodeURIComponent(JSON.stringify(a));a=this.script+"?r="+Math.floor(1E5*Math.random())+"&cmd="+a;$script(a)};c.prototype.setTargeting=function(a,b){null==this.targeting&&(this.targeting={});this.targeting[a]=
b};c.prototype.sizeMapping=function(){return new d};c.prototype.chooseSize=function(a){if("string"==typeof a)return a;if("function"==typeof a.build)a=a.build();else if(!(a.length&&2==a[0].length))return null;var b=0,c=0;"number"==typeof window.innerWidth?(b=window.innerWidth,c=window.innerHeight):document.documentElement&&document.documentElement.clientWidth?(b=document.documentElement.clientWidth,c=document.documentElement.clientHeight):document.body&&document.body.clientWidth&&(b=document.body.clientWidth,
c=document.body.clientHeight);if(0==b||0==c)return null;a.sort(function(a,b){var c=a[1]||[],d=b[1]||[];return(2==d.length?d[0]*d[1]:0)-(2==c.length?c[0]*c[1]:0)});for(var d=0;d<a.length;++d){var f=a[d][0][0],m=a[d][0][1];if(!(f&&f>b||m&&m>c))return a=a[d][1]||[],2==a.length?a[0]+"x"+a[1]:null}return null};c.prototype.registerSlot=function(){null==this.slotEvents&&(this.slotEvents=[]);var a={};if("string"==typeof arguments[0]){if(a={name:arguments[0]},1<arguments.length){var b=this.chooseSize(arguments[1]);
b&&(a.sizes=b)}}else a=arguments[0];this.slotEvents.push(a)};c.prototype.asyncNavegg=function(a){function b(){return f.murmurhash3_32_gc((f.getData("pid")||"")+Math.round((new Date).getTime()/216E5),0).toString(16)}var c=f.getData("navegg_logged"),d=f.getData("navegg_usr");if(b()!==c||!d){var r=this;window.nvg33590=new function(){this.start=function(a,c,d){"string"==typeof c&&(""!==c&&"string"==typeof d&&""!==d)&&r.push(["navegg_ids",c.replace(/:/g,"_"),d.replace(/:/g,"_")]);r.onFinish(function(c){c&&
(f.setData("navegg_logged",b()),f.setData("navegg_usr",a))});$script("//cdn.navdmp.com/req?v=7&upd=1&acc=33590&id="+a+"&tit="+escape(window.document.title))};this.include=this.doSync=function(){}};$script("//usr.navdmp.com/usr?v=7&acc=33590&new=1&wst=0",a)}else a(),$script("//navdmp.com/req?v=7&upd=1&acc=33590&id="+d+"&tit="+escape(window.document.title))};c.prototype.onFinish=function(a){f.isArray(this.finishCallback)?this.finishCallback.push(a):a(this.finishCallback)};c.prototype.callOnFinish=function(a){if(f.isArray(this.finishCallback)){for(var b=
0;b<this.finishCallback.length;++b)this.finishCallback[b](a);this.finishCallback=a}};f.RemoteCommand=c})();
(function(c){var d=function(){var d=window.atingePartner;if(c.isArray(d)){var a=new c.RemoteCommand(c.url("/partners/request"));window.atingePartner=a;a.push(["@ver",1]);a.push(["@bi",c.browserId]);var b;(b=c.getData("pid"))&&a.push(["@pid",b]);(b=c.nullEmptyString(document.title))&&a.push(["tl",b]);(b=c.nullEmptyString(document.referrer))&&a.push(["rf",b]);b=0;window.localStorage&&(b|=1);window.sessionStorage&&(b|=2);window.orientation&&(b|=4);var e;try{e=window.self!==window.top}catch(g){e=!0}e&&
(b|=8);a.push(["ft",b]);a.push(["ph",c.pluginHash()]);isNaN(screen.width)||a.push(["sww",screen.width]);isNaN(screen.height)||a.push(["swh",screen.height]);isNaN(screen.colorDepth)||a.push(["sc",screen.colorDepth]);isNaN(window.screenX)?isNaN(window.screenLeft)||a.push(["sx",window.screenLeft]):a.push(["sx",window.screenX]);isNaN(window.screenY)?isNaN(window.screenTop)||a.push(["sy",window.screenTop]):a.push(["sy",window.screenY]);e=new Date;a.push(["t",e.getTime()]);a.push(["tz",e.getTimezoneOffset()]);
a.push.apply(a,d)}};c.doNotStart?c.initializer=d:d()})(window.atinge);
