(function(e,f,h,F){function u(a){(e._rt_ajaxImg||new Image(1,1)).src=a}function G(a){var b=f.getElementsByTagName("meta");for(i=0;i<b.length;i++)if(b[i].getAttribute("property")==a)return encodeURIComponent(b[i].getAttribute("content"));return""}function A(){return e.pageYOffset||f.body.scrollTop||f.documentElement.scrollTop||0}function H(){var a=f.body,b=f.documentElement;return Math.max(a.scrollHeight||0,b.scrollHeight||0,a.offsetHeight||0,b.offsetHeight||0,a.clientHeight||0,b.clientHeight||0)}
function I(a){B&&clearTimeout(B);J=A();!0===a?k=Math.max((A()+(e.innerHeight||f.documentElement.clientHeight||f.body.clientHeight||0))/H()*100,k):B=setTimeout(function(){k=Math.max((A()+(e.innerHeight||f.documentElement.clientHeight||f.body.clientHeight||0))/H()*100,k)},400)}function n(a,b){a!=v&&(p&&"hidden"==a&&(w+=b.getTime()-p.getTime()),p=b);K=b;v=a}function q(){n("visible",new Date)}function da(){6<++L&&(L=0,q())}function C(){n("hidden",new Date)}function D(a,b){for(var c=0;c<a.length;c++)g(a[c],
b)}function M(){for(x in N)if(x in f){O=N[x];break}}function P(){Q(function(){Q()?q():C()})}function R(){D(ea,q);D(fa,C);D(ga,da);g("beforeunload",function(){n("hidden",new Date)})}function S(){var a=new Date;3E4<a.getTime()-K.getTime()&&C();ha&&(y&&1E4<a.getTime()-y.getTime()&&(n("hidden",y),n("visible",a)),y=a)}var T=function(a){a.hash="";h.hash="";"function"==typeof F.replaceState?F.replaceState({},"",h.href.slice(0,-1)):h.replace("#")},m=encodeURIComponent,g=function(a,b){var c=e.addEventListener;
if(c)return c(a,b,!0);(c=e.attachEvent)&&c("on"+a,b)},U=function(a){var b,c=b=null,d=null;/#[-A-Za-z0-9]+[,]\w+/.test(a)&&(a=a.substring(1).split(","),b=a[0],c=a[1],d=a[2]);return(b=b&&c?{experiment:b,version:c,testId:d}:null)?(u("//globo-ab.globo.com/convert/"+b.experiment+"/"+b.version+"?testId="+b.testId),!0):!1},E=function(){var a=f.createElement("a");a.href=r(h);(a=a.hostname)&&0===a.indexOf("m.")&&(a=a.substring(2,a.length));return a.replace(".globo.com","").replace(".globoi.com","")},r=function(a){var b;
e.glb_realtime_map&&e.glb_realtime_map.url?b=glb_realtime_map.url:(b=V("url"),b||(a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:"")),b=a.origin+a.pathname));a=b?a.hash?b.split("#")[0]+a.hash:b:void 0;return a},V=function(a){if(f.querySelector)return(f.querySelector('meta[property="og:'+a+'"]')||{}).content;for(var b=f.getElementsByTagName("meta"),c=b.length,d=0;d<c;d++)if(b[d].attributes.property&&b[d].attributes.property.value==="og:"+a)return b[d].attributes.content.value},k,
J,B=null,W=!1,X=function(){k=0;if(W)return!1;W=!0;g("load",function(){g("scroll",I);I(!0)});return!1},v,p,K,x,O,ea="focus focusin pageshow scroll keydown click".split(" "),ga=["mouseover","mousemove"],fa=["pagehide","blur","focusout"],y,w=0,L=0,ha=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?!0:!1,N={hidden:"visibilitychange",webkitHidden:"webkitvisibilitychange",msHidden:"msvisibilitychange"},Q=function(a){a&&(g(O,a),a());return!f[x]},z=0,Y=function(){g("click",function(){z+=1})},Z=function(a,
b,c,d,e,f,h){b=m(b.split("#")[0]);a="//horizon.globo.com/auth-session/activity/"+a+"/track?time="+c+"&object="+b+"&scroll="+parseFloat(d).toFixed(2)+"&clicks="+e+"&scrollabs="+f+"&objecttype="+h;u(a)},t=function(a,b){Z(a,b,w+((new Date).getTime()-p.getTime()),k,z,J,G("metrics:type")||G("og:type")||"")},aa=function(){q();M();setTimeout(P,300);R();X();Y();var a=E(),b=r(h);setInterval(function(){S();"hidden"!=v&&t(a,b)},1E4);g("beforeunload",function(){t(a,b)})},V=function(a){if(f.querySelector)return(f.querySelector('meta[property="og:'+
a+'"]')||{}).content;for(var b=f.getElementsByTagName("meta"),c=b.length,d=0;d<c;d++)if(b[d].attributes.property&&b[d].attributes.property.value==="og:"+a)return b[d].attributes.content.value},ba=function(a){a=["object.url="+m(a.url),"user.referer="+m(f.referrer),"object.meta.title="+m(a.title||"-"),"object.meta.product="+m(a.site),"object.meta.tags="+m((a.categories||[]).join(",")),"action.name=read","_="+(new Date).getTime()];u("http://rt.globo.com/pv.gif?"+a.join("&").replace(/%20/g,"+"))},ca=
function(){e.glb_realtime_map||(e.glb_realtime_map={site:E(),categories:["content"],url:r(h)});"undefined"===typeof REALTIME&&(REALTIME=void 0);var a;a=glb_realtime_map.categories;if(REALTIME&&REALTIME.categories)for(var b=REALTIME.categories(),c=b.length,d=0;d<c;d++){var l;a:{l=b[d];var g=a;if(g.indexOf)l=g.indexOf(l);else{for(var k=0,n=g.length;k<n;k++)if(g[k]===l){l=k;break a}l=-1}}-1==l&&(a=a.concat(b[d]))}b=r(h);a:{if(c=f.getElementsByTagName("meta"))for(d=0;d<c.length;d++)if(l=c[d],"title"==
l.getAttribute("name")){c=l.getAttribute("content");break a}c=void 0}a={url:b,title:c,site:glb_realtime_map.site,categories:a};b=m(a.site);c=m(a.url&&a.url.split("#")[0]);d=m(f.referrer);u("//horizon.globo.com/auth-session/activity/"+b+"/pageview?object="+c+"&Referrer="+d);ba(a)},ia=function(a,b){var c=RegExp("[?&]"+b+"=([^&]*)").exec(a);return c&&decodeURIComponent(c[1].replace(/\+/g," "))},t=function(a,b){Z(a,b,w+((new Date).getTime()-p.getTime()),k,z)},aa=function(){if(!e.glb_realtime_map||void 0==
e.glb_realtime_map.enableTrack||0!=e.glb_realtime_map.enableTrack){q();M();setTimeout(P,300);R();X();Y();var a=E(),b=r(h);setInterval(function(){S();"hidden"!=v&&t(a,b)},1E4);g("beforeunload",function(){t(a,b)})}};e.pvm||(e.pvm={hash:h.hash,query:h.search},e.generatePageView=ca,"#na"===pvm.hash||"true"===ia(pvm.query,"noAudience")?T(pvm):e.glb_realtime_map&&void 0!=e.glb_realtime_map.enableTrack&&1==e.glb_realtime_map.manualPageView||ca(),U(pvm.hash)&&T(pvm),aa(),e.sendPageViewToServer=ba,e.convertRecAb=
U)})(window,document,window.location,window.history);
